
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: buysale_development
  username: postgres
  password: Power003


test:
  <<: *default
  database: buysale_test
  username: postgres
  password: Power003

production:
  <<: *default
  database: buysale_production
  username: buysale
  password: <%= ENV["BUYSALE_DATABASE_PASSWORD"] %>
